version: '3.8'

services:
  generator:
    image: mobaijun/generator:latest
    container_name: generator
    ports:
      - "8889:8889"
    restart: unless-stopped
    environment:
      - DB_HOST=192.168.110.201
      - DB_PORT=3306
      - DB_NAME=april-generator
      - DB_USER=root
      - DB_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
