name: CI

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  # 默认为 Docker Hub，如为空则使用 docker.io
  REGISTRY: ''
  # 自定义镜像名称
  IMAGE_NAME: 'generator'
  # 组合用户名和镜像名称作为完整的镜像名称
  FULL_IMAGE_NAME: '${{ env.USERNAME }}/${{ env.IMAGE_NAME }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: 使用 Maven 构建
        run: mvn -B clean package --file pom.xml
      - name: 构建 Docker 镜像
        run: docker build . --file ./ballcat-codegen-backend/src/main/resources/docker/Dockerfile --tag ${{env.FULL_IMAGE_NAME}}:latest
      - name: 输出分支名称
        run: echo $GITHUB_REF_NAME
      - name: 检查生成的 JAR 文件
        run: ls -l ./ballcat-codegen-backend/target/

      # 登录到 Docker 注册表
      - name: 登录到 Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 提取 Docker 元数据（标签、标签）
      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          tags: |
            # 为默认分支设置最新标签
            type=raw,value=latest,enable={{is_default_branch}}
            # 标签事件
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      # 推送镜像
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}